// flow-typed signature: 7849d9ce4b390afcfc917a08445a20eb
// flow-typed version: <<STUB>>/adbkit-fb_v2.10.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'adbkit-fb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'adbkit-logcat-fb' {
  const exports:any
  export = exports
}

