// flow-typed signature: 7849d9ce4b390afcfc917a08445a20eb
// flow-typed version: <<STUB>>/adbkit-fb_v2.10.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'adbkit-fb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'adbkit-fb' {
  const exports:any
  export = exports
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'adbkit-fb/lib/adb' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/auth' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/client' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-serial/forward' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-serial/getdevicepath' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-serial/getserialno' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-serial/getstate' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-serial/listforwards' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-serial/waitfordevice' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/clear' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/framebuffer' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/getfeatures' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/getpackages' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/getproperties' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/install' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/isinstalled' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/listreverses' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/local' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/log' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/logcat' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/monkey' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/reboot' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/remount' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/reverse' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/root' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/screencap' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/shell' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/startactivity' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/startservice' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/sync' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/tcp' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/tcpip' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/trackjdwp' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/uninstall' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/usb' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host-transport/waitbootcomplete' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host/connect' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host/devices' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host/deviceswithpaths' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host/disconnect' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host/kill' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host/trackdevices' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host/transport' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/command/host/version' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/connection' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/dump' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/framebuffer/rgbtransform' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/keycode' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/linetransform' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/parser' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/proc/stat' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/protocol' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/sync' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/sync/entry' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/sync/pulltransfer' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/sync/pushtransfer' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/sync/stats' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/tcpusb/packet' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/tcpusb/packetreader' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/tcpusb/rollingcounter' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/tcpusb/server' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/tcpusb/service' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/tcpusb/servicemap' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/tcpusb/socket' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/tracker' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/adb/util' {
  const exports:any
  export = exports
}

declare module 'adbkit-fb/lib/cli' {
  const exports:any
  export = exports
}

// Filename aliases
declare module 'adbkit-fb/index' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/index.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/auth.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/client.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-serial/forward.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-serial/getdevicepath.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-serial/getserialno.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-serial/getstate.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-serial/listforwards.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-serial/waitfordevice.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/clear.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/framebuffer.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/getfeatures.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/getpackages.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/getproperties.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/install.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/isinstalled.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/listreverses.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/local.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/log.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/logcat.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/monkey.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/reboot.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/remount.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/reverse.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/root.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/screencap.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/shell.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/startactivity.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/startservice.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/sync.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/tcp.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/tcpip.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/trackjdwp.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/uninstall.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/usb.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host-transport/waitbootcomplete.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host/connect.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host/devices.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host/deviceswithpaths.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host/disconnect.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host/kill.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host/trackdevices.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host/transport.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/command/host/version.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/connection.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/dump.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/framebuffer/rgbtransform.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/keycode.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/linetransform.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/parser.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/proc/stat.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/protocol.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/sync.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/sync/entry.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/sync/pulltransfer.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/sync/pushtransfer.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/sync/stats.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/tcpusb/packet.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/tcpusb/packetreader.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/tcpusb/rollingcounter.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/tcpusb/server.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/tcpusb/service.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/tcpusb/servicemap.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/tcpusb/socket.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/tracker.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/adb/util.js' {
  const exports:any
  export = exports
}
declare module 'adbkit-fb/lib/cli.js' {
  const exports:any
  export = exports
}
