// flow-typed signature: 9f53cea57f90e7b45880ce45965ffa06
// flow-typed version: <<STUB>>/@material-ui/utils_v3.0.0-alpha.3/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/utils/chainPropTypes' {
  declare module.exports: any;
}

declare module '@material-ui/utils/componentPropType' {
  declare module.exports: any;
}

declare module '@material-ui/utils/es/chainPropTypes' {
  declare module.exports: any;
}

declare module '@material-ui/utils/es/componentPropType' {
  declare module.exports: any;
}

declare module '@material-ui/utils/es/exactProp' {
  declare module.exports: any;
}

declare module '@material-ui/utils/es/getDisplayName' {
  declare module.exports: any;
}

declare module '@material-ui/utils/es/index' {
  declare module.exports: any;
}

declare module '@material-ui/utils/es/ponyfillGlobal' {
  declare module.exports: any;
}

declare module '@material-ui/utils/exactProp' {
  declare module.exports: any;
}

declare module '@material-ui/utils/getDisplayName' {
  declare module.exports: any;
}

declare module '@material-ui/utils/index.es' {
  declare module.exports: any;
}

declare module '@material-ui/utils/ponyfillGlobal' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/utils/chainPropTypes.js' {
  declare module.exports: $Exports<'@material-ui/utils/chainPropTypes'>;
}
declare module '@material-ui/utils/componentPropType.js' {
  declare module.exports: $Exports<'@material-ui/utils/componentPropType'>;
}
declare module '@material-ui/utils/es/chainPropTypes.js' {
  declare module.exports: $Exports<'@material-ui/utils/es/chainPropTypes'>;
}
declare module '@material-ui/utils/es/componentPropType.js' {
  declare module.exports: $Exports<'@material-ui/utils/es/componentPropType'>;
}
declare module '@material-ui/utils/es/exactProp.js' {
  declare module.exports: $Exports<'@material-ui/utils/es/exactProp'>;
}
declare module '@material-ui/utils/es/getDisplayName.js' {
  declare module.exports: $Exports<'@material-ui/utils/es/getDisplayName'>;
}
declare module '@material-ui/utils/es/index.js' {
  declare module.exports: $Exports<'@material-ui/utils/es/index'>;
}
declare module '@material-ui/utils/es/ponyfillGlobal.js' {
  declare module.exports: $Exports<'@material-ui/utils/es/ponyfillGlobal'>;
}
declare module '@material-ui/utils/exactProp.js' {
  declare module.exports: $Exports<'@material-ui/utils/exactProp'>;
}
declare module '@material-ui/utils/getDisplayName.js' {
  declare module.exports: $Exports<'@material-ui/utils/getDisplayName'>;
}
declare module '@material-ui/utils/index.es.js' {
  declare module.exports: $Exports<'@material-ui/utils/index.es'>;
}
declare module '@material-ui/utils/index' {
  declare module.exports: $Exports<'@material-ui/utils'>;
}
declare module '@material-ui/utils/index.js' {
  declare module.exports: $Exports<'@material-ui/utils'>;
}
declare module '@material-ui/utils/ponyfillGlobal.js' {
  declare module.exports: $Exports<'@material-ui/utils/ponyfillGlobal'>;
}
