// flow-typed signature: f54d1a21f61edf90c31bf9de9fb504f7
// flow-typed version: <<STUB>>/multicast-dns_v7.2.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multicast-dns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multicast-dns' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'multicast-dns/cli' {
  declare module.exports: any;
}

declare module 'multicast-dns/example' {
  declare module.exports: any;
}

declare module 'multicast-dns/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'multicast-dns/cli.js' {
  declare module.exports: $Exports<'multicast-dns/cli'>;
}
declare module 'multicast-dns/example.js' {
  declare module.exports: $Exports<'multicast-dns/example'>;
}
declare module 'multicast-dns/index' {
  declare module.exports: $Exports<'multicast-dns'>;
}
declare module 'multicast-dns/index.js' {
  declare module.exports: $Exports<'multicast-dns'>;
}
declare module 'multicast-dns/test.js' {
  declare module.exports: $Exports<'multicast-dns/test'>;
}
