// flow-typed signature: 91d9906edc8c560cdac4e9bc5896b029
// flow-typed version: <<STUB>>/react-valid-props_v1.0.12/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-valid-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-valid-props' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-valid-props/dist/react-valid-props' {
  declare module.exports: any;
}

declare module 'react-valid-props/dist/react-valid-props.spec' {
  declare module.exports: any;
}

declare module 'react-valid-props/src/react-valid-props' {
  declare module.exports: any;
}

declare module 'react-valid-props/src/react-valid-props.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-valid-props/dist/react-valid-props.js' {
  declare module.exports: $Exports<'react-valid-props/dist/react-valid-props'>;
}
declare module 'react-valid-props/dist/react-valid-props.spec.js' {
  declare module.exports: $Exports<'react-valid-props/dist/react-valid-props.spec'>;
}
declare module 'react-valid-props/src/react-valid-props.js' {
  declare module.exports: $Exports<'react-valid-props/src/react-valid-props'>;
}
declare module 'react-valid-props/src/react-valid-props.spec.js' {
  declare module.exports: $Exports<'react-valid-props/src/react-valid-props.spec'>;
}
