// flow-typed signature: d2bb59c132c72fa1676faea473007567
// flow-typed version: <<STUB>>/typeguard_v0.0.13/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeguard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeguard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typeguard/dist/Guards' {
  declare module.exports: any;
}

declare module 'typeguard/dist/index' {
  declare module.exports: any;
}

declare module 'typeguard/dist/test/Guards.spec' {
  declare module.exports: any;
}

declare module 'typeguard/dist/test/Tools.spec' {
  declare module.exports: any;
}

declare module 'typeguard/dist/Tools' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typeguard/dist/Guards.js' {
  declare module.exports: $Exports<'typeguard/dist/Guards'>;
}
declare module 'typeguard/dist/index.js' {
  declare module.exports: $Exports<'typeguard/dist/index'>;
}
declare module 'typeguard/dist/test/Guards.spec.js' {
  declare module.exports: $Exports<'typeguard/dist/test/Guards.spec'>;
}
declare module 'typeguard/dist/test/Tools.spec.js' {
  declare module.exports: $Exports<'typeguard/dist/test/Tools.spec'>;
}
declare module 'typeguard/dist/Tools.js' {
  declare module.exports: $Exports<'typeguard/dist/Tools'>;
}
