/**
 * Flowtype definitions for index
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.8.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module "@material-ui/core/styles" {
    declare export {
    default as createGenerateClassName
  } from "@material-ui/styles/createGenerateClassName";
    declare export {
    default as createMuiTheme,
    Theme,
    Direction
  } from "@material-ui/core/styles/createMuiTheme";
    declare export {default as jssPreset} from "@material-ui/core/styles/jssPreset";
    declare export {default as MuiThemeProvider} from "@material-ui/core/styles/MuiThemeProvider";
    declare export {default as createStyles} from "@material-ui/core/styles/createStyles";
    declare export {
    default as withStyles,
    WithStyles,
    StyleRules,
    StyleRulesCallback,
    StyledComponentProps
  } from "@material-ui/core/styles/withStyles";
    declare export {default as withTheme, WithTheme} from "@material-ui/core/styles/withTheme";
};
